language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
branches:
 only:
 - master
 - dev

env:
  - SUNDIALS_INCLUDEDIR="${HOME}/sundials-3.1.1/include" SUNDIALS_LIBDIR="${HOME}/sundials-3.1.1/lib" SUNDIALS_INST="${HOME}/sundials-3.1.1" LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/sundials-3.1.1/lib:/usr/local/lib"
  
before_install:
 - sudo apt-get install -y --no-install-recommends fort77 gfortran libmpfr-dev libflint-2.5.2 libflint-dev libopenblas-dev liblapack-dev libgmp-dev yasm
 - pip install -r docker/requirements.txt
 - source docker/utils/install_sundials.sh
 - pip install scikits.odes==2.4.1
 - pip install pytest-cov
install:
 - cd $TRAVIS_BUILD_DIR
 - pip install -e .

script:
 - py.test --cov=./

after_success:
 - pip install codecov; codecov;
